// Generate the worker bundle for public agent discovery from the repo-root llms.txt and canonical CLI skill.
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const here = import.meta.dir
const root = join(here, '..', '..', '..')
const llms = readFileSync(join(root, 'llms.txt'), 'utf8')
const skill = readFileSync(join(root, 'packages', 'cli', 'internal', 'cli', 'SKILL.md'), 'utf8')

const out = `// GENERATED by scripts/build-agent-docs.ts. Edit /llms.txt or the canonical CLI SKILL.md instead.
export const LLMS_TXT = ${JSON.stringify(llms)}
export const POSTPLAN_SKILL_MD = ${JSON.stringify(skill)}
`

writeFileSync(join(here, '..', 'src', 'agent-docs.ts'), out)
console.log(`agent docs: llms ${llms.length}B + skill ${skill.length}B → src/agent-docs.ts`)
