import { writeFileSync } from 'node:fs'
import { join } from 'node:path'

const srcDir = join(import.meta.dir, '..', 'src', 'mermaid')
const built = await Bun.build({
  entrypoints: [join(srcDir, 'client.ts')],
  minify: true,
  format: 'iife',
  target: 'browser',
})
if (!built.success) throw new AggregateError(built.logs, 'Mermaid client build failed')
const js = await built.outputs[0].text()
const version = new Bun.CryptoHasher('sha256').update(js).digest('hex').slice(0, 8)
writeFileSync(
  join(srcDir, 'bundle.ts'),
  `// GENERATED by scripts/build-mermaid.ts.\nexport const MERMAID_JS = ${JSON.stringify(js)}\nexport const MERMAID_VERSION = ${JSON.stringify(version)}\n`,
)
console.log(`Mermaid bundle: ${js.length}B → v${version}`)
